.\"
.\" SPDX short identifier: BSD-2-Clause
.\"
.\" Copyright (c) 2022 KusaReMKN.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright notice,
.\"    this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd 24th February 2022
.Dt L2WOL 1
.Os
.Sh NAME
.Nm l2wol
.Nd despatch Wake-on-LAN magic packets on Layer 2
.Sh SYNOPSIS
.Nm
.Op Fl b
.Op Fl i Ar interface
.Ar destination ...
.Sh DESCRIPTION
The
.Nm
utility wakes up
.Ar destination Ns No s
by despatching Wake-on-LAN magic packets on Layer 2.
Obviously,
.Ar destination Ns No s
need to support Wake-on-LAN technology.
Packets will be despatched from the first available network interface found,
or from
.Ar interface
if the
.Fl i
option is specified.
If the
.Fl b
option is specified,
packets will be broadcast.
.Sh FILES
.Bl -tag -width "/dev/bpf" -compact
.It Pa /dev/bpf
Berkeley Packet Filter
.Pq Bx No Only
.El
.Sh EXIT STATUS
.Ex -std
.Sh EXAMPLES
The command:
.Pp
.Dl % l2wol 00:00:5e:00:53:01
.Pp
will wakes up the computer has a network interface with MAC address
.Ql 00:00:5e:00:53:01 .
.Pp
The command:
.Pp
.Dl % l2wol -i em0 00:00:5e:00:53:87 00:00:5e:00:53:29
.Pp
will despatch magic packets from the network interface named
.Ql em0 .
.Sh SEE ALSO
.Xr getifaddrs 3 ,
.Xr ifconfig 8
.Pp
.Xr ethers 3 ,
.Xr bpf 4 ,
.In net/if_dl.h
on FreeBSD
.Pp
.Xr ether_aton 3 ,
.Xr packet 7
on Linux
.Sh COPYRIGHT
Copyright \(co 2022 KusaReMKN.
All rights reserved.
.Pp
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
.Bl -enum
.It
Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.
.It
Redistributions in binary form must reproduce the above copyright notice, this
list of conditions and the following disclaimer in the documentation and/or
other materials provided with the distribution.
.El
.Pp
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.Dq AS IS
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.Sh BUGS
MAC addresses separated by a dash instead of a colon
.Pq e.g. Ql 00-00-5e-00-53-01
are not supported.
